### ISSUE TITLE
findOneAndUpdate unexpectedly throws exception when condition finds no document to update

### ISSUE THREAD

**Issue by DanStory** [swimlane/mongtype#20]
`MongoRepository.findOneAndUpdate` does not properly handle when the criteria isn't met and no document is found.
Version: 4.1.0
```
TypeError: Cannot read property 'then' of null
    at Repository.invokeEvents (/node_modules/mongtype/src/Repository.ts:352:29)
    at Repository.findOneAndUpdate (/node_modules/mongtype/src/Repository.ts:210:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by DanStory** [comment]
Fixed with v4.2.1 release
